[package]
name = "xinghuo-geom"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
glam = { version = "0.20.5", features = ["bytemuck"] }
bytemuck = { version = "1.9.1", features = ["derive"] }

[features]
default = ["bytemuck"]
bytemuck = []
